# Generated by Django 3.1.6 on 2021-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210222_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='enroll_no',
            field=models.TextField(default=170770107203, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='username',
            field=models.TextField(max_length=100),
        ),
    ]
