# Generated by Django 3.1.6 on 2021-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210321_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindata',
            name='admin',
        ),
        migrations.AddField(
            model_name='admindata',
            name='enroll_no',
            field=models.TextField(default=101, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
