# Generated by Django 3.1.6 on 2021-03-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_resources_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='placements',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='resources',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
