# Generated by Django 3.1.6 on 2021-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210321_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('type', models.TextField(max_length=50)),
                ('dept_id', models.TextField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
