# Generated by Django 3.1.6 on 2021-03-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210321_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.DeleteModel(
            name='Placements',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
