# Generated by Django 3.1.6 on 2021-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_clubs_placements_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placements',
            old_name='title',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='placements',
            name='file_link',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placements',
            name='file_name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
