# Generated by Django 3.1.6 on 2021-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20210322_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placements',
            old_name='file_name',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='placements',
            old_name='file_link',
            new_name='documentUrl',
        ),
        migrations.AddField(
            model_name='placements',
            name='form_link',
            field=models.TextField(default='xyz', max_length=100),
            preserve_default=False,
        ),
    ]
